### ISSUE TITLE
Store will need to be async friendly

### ISSUE THREAD

**Issue by disturbing** [bappr/proxless#1]
https://github.com/bappr/kube-proxless/blob/5d6ef8af2b3b9fd9cc6d17f94387e1a68e1fa608/internal/store/store.go#L1

Due to access from threads from both fasthttp and k8s, you will need to make the store threadsafe. Recommend using a readwrite lock since writes will be low concurrency.

**Comment by bakayolo** [comment]
Thanks.
Fixed
