### ISSUE TITLE
Memory leak on fasthttp tooling

### ISSUE THREAD

**Issue by disturbing** [bappr/proxless#2]
https://github.com/bappr/kube-proxless/blob/5d6ef8af2b3b9fd9cc6d17f94387e1a68e1fa608/internal/server/server.go#L29

With fasthttp, need to release the requests. It's using a "pool" design pattern for high concurrency.

```
defer fasthttp.ReleaseRequest(req)
defer fasthttp.ReleaseResponse(resp)
```

**Comment by bakayolo** [comment]
Thanks. Fixed in the PR.
